name: ghostcloud
version: git
grade: stable
confinement: strict
base: core24
summary: A modern cross-platform client for Nextcloud, ownCloud, WebDav.
description: |
  Allows you to easily access your NextCloud, ownCloud and WebDav
  instances with a cross-platform, native Free Software application.
  
  Features:
    - Support for NextCloud, ownCloud & WebDav
    - File management
    - Document previews
    - Video & audio previews
    - Storage usage information
  
  Also available on Android & SailfishOS.

platforms:
  amd64:
  arm64:
  armhf:

apps:
  ghostcloud:
    environment:
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
    command: usr/bin/harbour-owncloud
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - opengl
      - alsa
      - pulseaudio
      - home
      - removable-media
      - network
      - audio-playback

plugs:
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/share/X11/xkb:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/X11/xkb
  /usr/share/icons:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/qt5:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/qt5
  /usr/share/alsa:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/alsa

parts:
  app:
    plugin: qmake
    source: .
    qmake-parameters:
      - CONFIG+=noadditionals
      - CONFIG+=quickcontrols
    qmake-project-file: harbour-owncloud.pro
    build-packages:
      - make
      - qt5-qmake
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - qtmultimedia5-dev
      - libqt5webkit5-dev
      - qtbase5-dev
      - qtquickcontrols2-5-dev
      - qml-module-qtquick2
      - qml-module-qtgraphicaleffects
      - qml-module-qtquick-window2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-extras
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-controls
      - qml-module-qt-labs-settings
      - qml-module-qtquick-localstorage
    override-build: |
        craftctl default
        #cd $CRAFT_PART_SRC
        #qmake CONFIG+=noadditionals CONFIG+=quickcontrols
        #make -j$(nproc --all)
        #DESTDIR=$CRAFT_PART_INSTALL make install
    override-prime: |
        craftctl default
        mkdir -p ${CRAFT_PRIME}/bin
        cp -a /snap/lomiri-ui-toolkit-core24/current/command-chain/lomiri-launch ${CRAFT_PRIME}/bin/lomiri-launch
  gpu-2404:
    after:
      - app
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
